spring:
  datasource:
    url: jdbc:mysql://training.czp3u6imlliu.ap-southeast-1.rds.amazonaws.com:3306/eCommerce
    username: admin
    password: testing1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      ventail: DEBUG