server:
    port: 8787

spring:
  datasource:
    url: jdbc:mysql://training.cyitrkbm82ap.ap-northeast-1.rds.amazonaws.com:3306/eCommerce
    username: admin
    password: testing1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      ventail: DEBUG