server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://busmapper.cyitrkbm82ap.ap-northeast-1.rds.amazonaws.com:3306/eCommerce
#    url: jdbc:mysql://training.czp3u6imlliu.ap-southeast-1.rds.amazonaws.com:3306/eCommerce
    username: admin
    password: qwerty1234
#    password: testing1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      ventail: DEBUG